"""empty message

Revision ID: 45320b1bc860
Revises: 
Create Date: 2021-02-28 21:25:52.198271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45320b1bc860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_title_key', 'movies', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movies_title_key', 'movies', ['title'])
    # ### end Alembic commands ###
