"""empty message

Revision ID: d85c175fb13c
Revises: 
Create Date: 2021-02-21 11:51:21.049638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85c175fb13c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actors_name_key', 'actors', type_='unique')
    op.create_unique_constraint(None, 'movies', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.create_unique_constraint('actors_name_key', 'actors', ['name'])
    # ### end Alembic commands ###
